### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by rlabrecque** [minddocdev/buzzfeed-sso#2]
In the README:

```
# values.yaml
[...]

proxy:
  cluster: dev

google:
  adminEmail: iamtheadmin@email.coolcompany.foo
```

Should be:

```
# values.yaml
[...]

cluster: dev

provider:
  google:
    adminEmail: iamtheadmin@email.coolcompany.foo
```

ingress & upstreams should also be added to the values.yaml example IMO.
