### ISSUE TITLE
extraEnv overwrites required environment variables

### ISSUE THREAD

**Issue by rlabrecque** [minddocdev/buzzfeed-sso#3]
Specifying `.Values.auth.extraEnv` or `.Values.proxy.extraEnv` overwrites the default values which are required, resulting in an error.

```
  extraEnv:
    - name: STATSD_HOST
      value: localhost
    - name: STATSD_PORT
      value: "11111"
```

Would be nice if they didn't need to be re-specified when overriding.
